# Generated by Django 6.0 on 2026-01-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
