from django.shortcuts import render
from django.urls import reverse_lazy
from django.shortcuts import redirect
from .models import Status
from task_manager.labels.forms import StatusFrom
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import CreateView,UpdateView
from django.views.generic.edit import DeleteView
from django.views import View